config/routes.rb
Kwp14::Application.routes.draw do
  resources :roles
  resources :votes
  resources :users

  
  resources :topics 
  resources :administration do
    collection do
      get 'index'
      get 'encrypt'
    end
  end
  resources :comments 
  resources :users 
  resources :user_sessions 
   match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'topics#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :title, :body, :predecessor

  has_and_belongs_to_many :tags
  has_many :comments
  has_many :votes

  def setup
    @rating
  end

  def rating
    self[:rating].nil? ? recalculate_rating : self[:rating]
    
  end
    
  def recalculate_rating
    if votes.size == 0
      return @rating = 0
    end

    sum_of_votes = 0
    votes.each do |v|
      v.value = 0 if v.value.nil?
      sum_of_votes += v.value
    end
    topic_rating = sum_of_votes / votes.size
    write_attribute(:rating, topic_rating.round(2));
  end

  def date_of_last_comment
    comments.last.nil? ?  Time.new(2002) : comments.last.created_at
  end

  def has_tag(tag)
    tags.each do |t|
      if t.title == tag
        return true
      end
    end
    return false

  end

  def votecount
    return votes.size
  end




end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :require_user, :only => :show



  def index
    @topics = Topic.all()

    session[:filter_param] = params[:filter] if params[:filter]
    if(session[:filter_param] and session[:filter_param]!="no")
      @topics_filtered = [];
      @topics.each do |t|
        if t.has_tag(session[:filter_param])
          @topics_filtered.push t
        end
      end
      @topic_content = true
      @filter = session[:filter_param]
      @topics = @topics_filtered
    end

    session[:sort_param] = params[:sort] if params[:sort]
    if(session[:sort_param] and session[:sort_param]!="no")
       case session[:sort_param]
       when "Bewertungen" 
         then @topics.sort! {|a,b| b.rating <=> a.rating}
       when "Kommentare"
         then @topics.sort! {|a,b| b.date_of_last_comment <=> a.date_of_last_comment}
       end
    end
    
  end

  def show
    @id = params[:id]
    @topic = Topic.find(@id)

    @comment = Comment.new() #for the form partial
    @comment.topic = @topic
    @comment.user = current_user
    @comments = @topic.comments


    #if there is an old vote we just need to update
    @old_vote = Vote.where({:user_id => current_user, :topic_id => @id}).first

    if (@old_vote)
      @vote = @old_vote
    else
      @vote = Vote.new()
      @vote.topic = @topic
      @vote.user = current_user
    end

  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
 <%= f.hidden_field :id %> 
 <p> 
 <h2> Titel </h2>
 <%= f.text_field :title, cols: 100, rows: 1 %> </br>
 </p>
 <p> 
 <h2> Inhalt </h2>
 <%= f.text_area :body, cols: 100, rows: 4 %>
 </p>
 <%= f.submit 'Änderung Speichern' %>
<% end %>

<div id="all_comments">
  <% even = false %>
  <% @comments.each do |c| %>
    <% if even %>
      <div class="comment" style="background-color:#dddddd" >
    <%else%>
      <div class="comment"  >
    <%end%>
      <span class="comment_body">
        <%= simple_format c.body %>
      </span> - 
      <span class="comment_author">
        <%= c.user.first_name %> <%= c.user.last_name%>, <%=c.created_at %>
      </span>
    </div>
  <% even = !even %>
  <% end %>

</div>

app/views/topics/edit.html.erb
<h1> Aufgabe/Teilziel <%= @topic.title %> bearbeiten </h1>
<br />
<br />
<%= render :partial => 'form' %>

app/views/topics/index.html.erb
<% unless @topic_content.nil? %>
  <div class="content">
    <h2> <%= @filter %> </h2>
   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae mauris imperdiet libero cursus mollis. Proin nisi sapien, consequat sed dictum ac, pulvinar at augue. Donec vitae fermentum felis. Donec ut malesuada ante. Pellentesque ultricies ac justo ut eleifend. Curabitur pulvinar urna ac turpis consectetur, in vestibulum risus rutrum. Etiam ac arcu euismod, porttitor enim eu, vestibulum est. Etiam nulla risus, pharetra id lacinia eu, dignissim in turpis. Mauris ultricies magna at augue aliquam bibendum. Praesent turpis est, iaculis nec feugiat vitae, vehicula et nibh. Nullam nibh dui, semper sit amet quam rutrum, viverra lacinia lectus. In leo dui, dictum at nisl ut, ultricies condimentum justo.

   Nulla sit amet felis rutrum, congue nisl at, euismod enim. Integer et pharetra arcu. Vestibulum vel gravida velit. Mauris sed mauris porta, efficitur turpis eget, volutpat sem. Curabitur varius rhoncus ligula. Sed commodo lorem urna, ac fermentum lorem scelerisque nec. Nullam quis erat a augue volutpat efficitur ac non libero. In luctus libero ut rhoncus ultrices. 

  </div>
  

<% end %>

  <div class="content">
<table >
  <tr>
    <th align="left"> Nr </th>
    <th align="left"> Bewertung </th>
    <th align="left"> Schlagworte </th>
    <th align="left"> Aufgaben und Teilziele </th>
  </tr>
<% @topics.each do |t| %>
  <tr style="border-bottom:1px solid black; padding-bottom:40px; margin-bottom:40px">
    <td class="main_table"> <%= t.id %>. </td>
    <td valign="center" class="main_table">
      <div class="topic_menu" style="float:left; min-height:40px; width=300px; margin-right:40px">
        <div class="topic_rating"> <a name="topic_<%=t.id%>"  </a><%= t.rating %>  </div>
        <!--div class="topic_menu_item"> <%= link_to 'bewerten', topic_path(t.id)  %> </div-->
      </div>
    </td>
    <td valign="top" class="main_table">
      <div class="topic_title" style="margin-right:40px">
        <% t.tags.each do |tag| %>
        [<%= link_to tag.title, topics_path(:filter => tag.title) %>] <br />
        <% end %>
      </div>
    </td>
    <td valign="center" class="main_table">
      <div class="topic_content" style="float:left;">
        <%= link_to t.body, topic_path(t.id) %>
      </div>
    </td>
    <hruler>
  </tr >
  
<% end %>
  </div>

</table>

app/views/topics/show.html.erb
<h1> Aufgabe/Teilziel <%= @topic.title %></h1>
<br />
<br />
<div id="topic_body">
  <%= @topic.body %>
</div>
<br />
<br />
<br />
<br />
<% if current_user %>
  <div id="new_vote">
    <%= render :partial => 'votes/form' %>
  </div>
<br />
<br />
<br />
<br />
  <div id="new_comment">
    <%= render :partial => 'comments/form' %>
  </div>
<%end%>
<div id="all_comments">
  <% even = false %>
  <% @comments.each do |c| %>
    <% if even %>
      <div class="comment" style="background-color:#dddddd" >
    <%else%>
      <div class="comment"  >
    <%end%>
      <span class="comment_body">
        <%= simple_format c.body %>
      </span> - 
      <span class="comment_author">
        <%= c.user.first_name %> <%= c.user.last_name%>, <%=c.created_at %>
      </span>
    </div>
  <% even = !even %>
  <% end %>

</div>